{% set name = "module-utilities" %}
{% set version = "0.10.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/module_utilities-{{ version }}.tar.gz
  sha256: 600cddc4175d4943a298ad123ff50afe06aab61ab6a0ac8858f7497c74f19662

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  imports:
    - module_utilities
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/usnistgov/module-utilities
  summary: Collection of utilities to aid working with python modules.
  description: |
    `cached`: A module to cache class attributes and methods. Right now, this uses
    a standard python dictionary for storage.
    `docfiller`: A module to share documentation between methods.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
