{% set name = "module-utilities" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/module-utilities-{{ version }}.tar.gz
  sha256: e5673415f58cf68e46278bf028533fa25ef73bef26044f5e8e37e00839ae70d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - typing-extensions

test:
  imports:
    - module_utilities
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/module-utilities
  summary: Collection of utilities to aid working with python modules.
  description: |
    `cached`: A module to cache class attributes and methods. Right now, this uses
    a standard python dictionary for storage.
    `docfiller`: A module to share documentation between methods.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
